# Generated by Django 4.2.4 on 2023-11-13 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slotno', models.CharField(max_length=90)),
                ('fromtime', models.CharField(max_length=90)),
                ('totime', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=90)),
                ('lastname', models.CharField(max_length=90)),
                ('dob', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=90)),
                ('Qualification', models.CharField(max_length=90)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=90)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.login')),
            ],
        ),
        migrations.CreateModel(
            name='tutorialvedio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vedio', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vedios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vedio', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('work', models.CharField(max_length=100)),
                ('SCHEDULE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.schedule')),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=90)),
                ('lastname', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=90)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=90)),
                ('age', models.CharField(max_length=90)),
                ('photo', models.CharField(max_length=90)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.login')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.FloatField()),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.trainer')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.user')),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.order')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.product'),
        ),
        migrations.CreateModel(
            name='feedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('SCHEDULE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='diat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diatchart', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('TRAINER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.trainer')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.user')),
            ],
        ),
    ]
