# Generated by Django 4.2.4 on 2023-11-16 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymdiat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='TRAINER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymdiat.trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymdiat.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='TRAINER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymdiat.trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymdiat.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='TRAINER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymdiat.trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialvedio',
            name='TRAINER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymdiat.trainer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vedios',
            name='TRAINER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymdiat.trainer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('SCHEDULE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.schedule')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymdiat.user')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='BOOKING',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymdiat.booking'),
            preserve_default=False,
        ),
    ]
