# Generated by Django 4.2.4 on 2023-11-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymdiat', '0002_remove_schedule_date_attendance_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='TRAINER',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='USER',
        ),
        migrations.AddField(
            model_name='attendance',
            name='BOOKING',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymdiat.booking'),
            preserve_default=False,
        ),
    ]
