from django.urls import path

from gymdiat import views

urlpatterns = [
    path('',views.login1,name='login1'),
    path('logout',views.logout,name='logout'),
    path('logincode',views.logincode,name='logincode'),
    path('adminhome',views.adminhome,name='adminhome'),
    path('mngtrainer',views.mngtrainer,name='mngtrainer'),
    path('mngtrainerpost',views.mngtrainerpost,name='mngtrainerpost'),
    path('addtrainer',views.addtrainer,name='addtrainer'),
    path('addtrainerpost',views.addtrainerpost,name='addtrainerpost'),
    path('edittrainer/<int:id>',views.edittrainer,name='edittrainer'),
    path('edittrainerpost',views.edittrainerpost,name='edittrainerpost'),
    path('deletetrainer/<int:id>',views.deletetrainer,name='deletetrainer'),
    path('viewuser',views.viewuser,name='viewuser'),
    path('viewuserpost',views.viewuserpost,name='viewuserpost'),
    path('mngproduct',views.mngproduct,name='mngproduct'),
    path('mngproductpost',views.mngproductpost,name='mngproductpost'),
    path('addproduct',views.addproduct,name='addproduct'),
    path('addproductpost',views.addproductpost,name='addproductpost'),
    path('editproduct/<int:id>',views.editproduct,name='editproduct'),
    path('editproductpost',views.editproductpost,name='editproductpost'),
    path('deleteproduct/<int:id>',views.deleteproduct,name='deleteproduct'),
    path('mngschedule',views.mngschedule,name='mngschedule'),
    path('mngschedulepost',views.mngschedulepost,name='mngschedulepost'),
    path('addschedule',views.addschedule,name='addschedule'),
    path('addschedulepost',views.addschedulepost,name='addschedulepost'),
    path('editschedule/<int:id>',views.editschedule,name='editschedule'),
    path('editschedulepost',views.editschedulepost,name='editschedulepost'),
    path('deleteschedule/<int:id>',views.deleteschedule,name='deleteschedule'),
    path('mngfee',views.mngfee,name='mngfee'),
    path('addfee',views.addfee,name='addfee'),
    path('addfeepost',views.addfeepost,name='addfeepost'),
    path('deletefee/<int:id>',views.deletefee,name='deletefee'),
    path('viewreport',views.viewreport,name='viewreport'),
    path('vieworderandverify',views.vieworderandverify,name='vieworderandverify'),
    path('vieworderandverifypost',views.vieworderandverifypost,name='vieworderandverifypost'),
    path('acceptorder/<int:id>',views.acceptorder,name='acceptorder'),
    path('rejectorder/<int:id>',views.rejectorder,name='rejectorder'),
    path('viewrating',views.viewrating,name='viewrating'),
    path('viewratingpost',views.viewratingpost,name='viewratingpost'),
    path('pendinglist',views.pendinglist,name='pendinglist'),
    path('trainerhome',views.trainerhome,name='trainerhome'),
    path('viewschedule',views.viewschedule,name='viewschedule'),
    path('viewuser1',views.viewuser1,name='viewuser1'),
    path('viewuser1post',views.viewuser1post,name='viewuser1post'),
    path('viewrating1',views.viewrating1,name='viewrating1'),
    path('uploadeqpvedio',views.uploadeqpvedio,name='uploadeqpvedio'),
    path('addeqpvedio',views.addeqpvedio,name='addeqpvedio'),
    path('addqpvediopost',views.addqpvediopost,name='addqpvediopost'),
    path('deleteqpvedio/<int:id>',views.deleteqpvedio,name='deleteqpvedio'),
    path('mngattendance',views.mngattendance,name='mngattendance'),
    path('presentattendance/<int:id>',views.presentattendance,name='presentattendance'),
    path('absentattendance/<int:id>',views.absentattendance,name='absentattendance'),
    path('mngscheduleworkout',views.mngscheduleworkout,name='mngscheduleworkout'),
    path('addworkoutschedule',views.addworkoutschedule,name='addworkoutschedule'),
    path('mngdiatchart',views.mngdiatchart,name='mngdiatchart'),
    path('mngdiatchartpost',views.mngdiatchartpost,name='mngdiatchartpost'),
    path('adddiatchart',views.adddiatchart,name='adddiatchart'),
    path('adddiatchartpost',views.adddiatchartpost,name='adddiatchartpost'),
    path('deletediat/<int:id>',views.deletediat,name='deletediat'),
    path('mngtutorialvedio',views.mngtutorialvedio,name='mngtutorialvedio'),
    path('addvedio',views.addvedio,name='addvedio'),
    path('addvediopost',views.addvediopost,name='addvediopost'),
    path('deletevedio/<int:id>',views.deletevedio,name='deletevedio'),
    path('verifyschedulebooking',views.verifyschedulebooking,name='verifyschedulebooking'),
    path('acceptbooking/<int:id>',views.acceptbooking,name='acceptbooking'),
    path('rejectbooking/<int:id>',views.rejectbooking,name='rejectbooking'),
    path('viewfoodhistory',views.viewfoodhistory,name='viewfoodhistory'),
    path('viewfoodhistorypost',views.viewfoodhistorypost,name='viewfoodhistorypost'),



#_________________________________ANDROID_______________________


    path('logincode1', views.logincode1, name='logincode1'),
    path('registration', views.registration, name='registration'),
    # path('sendrating', views.sendrating, name='sendrating'),
    path('foodmanage', views.foodmanage, name='foodmanage'),
    path('viewtrainersendrating', views.viewtrainersendrating, name='viewtrainersendrating'),
    path('ratings', views.ratings, name='ratings'),
    path('orders', views.orders, name='orders'),
    path('viewtrainers', views.viewtrainers, name='viewtrainers'),
    path('viewtrainersearch', views.viewtrainersearch, name='viewtrainersearch'),
    path('viewdiatchart', views.viewdiatchart, name='viewdiatchart'),
    path('viewacceptedtrainers', views.viewacceptedtrainers, name='viewacceptedtrainers'),
    path('vieworderhistory', views.vieworderhistory, name='vieworderhistory'),
    path('payment_sucess', views.payment_sucess, name='payment_sucess'),
    path('vieweqpvedio', views.vieweqpvedio, name='vieweqpvedio'),
    path('viewtutorialvedio', views.viewtutorialvedio, name='viewtutorialvedio'),
    path('viewproduct', views.viewproduct, name='viewproduct'),
    path('viewproductsearch', views.viewproductsearch, name='viewproductsearch'),
    path('feepayment', views.feepayment, name='feepayment'),
    path('book', views.book, name='book'),

]
